version: '3'

services:
  app:
    build: .
    depends_on:
      - mariadb
      - db-rest
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=traindb
      - DB_DSN=root:password@tcp(mariadb:3306)/traindb
      - API_BASE_URL=http://db-rest:3000
      - MAX_RESULTS=200
      - DURATION=240
      - BUS=false
      - FERRY=false
      - TRAM=false
      - TAXI=false
      # Hildesheim HBF, Braunschweig HBF, Hannover HBF
      - STATION_IDS=8000169,8000049,8000152
    restart: always
    networks:
      default:

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: traindb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db:/var/lib/mysql
    restart: always
    networks:
      default:
      dns:
        ipv4_address: 172.28.0.65

  db-rest:
    image: docker.io/derhuerst/db-rest:6
    ports:
      - 127.0.0.1:3010:3000
    restart: always
    networks:
      default:

networks:
  dns:
    name: dns
    external: true
