{
 "title": "Train Tracker",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "train_name",
    "label": "Zugname",
    "query": "SELECT\n  train_name\nFROM traindb.trips"
   },
   {
    "name": "fahrt_nr",
    "label": "Fahrtnummer",
    "query": "SELECT\n  fahrt_nr\nFROM traindb.trips\nWHERE\n  train_name IN (${train_name:sqlstring})"
   }
  ]
 },
 "panels": [
  {
   "title": "Abfahrten Züge",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  latitude,\n  longitude,\n  train_name,\n  fahrt_nr,\n  destination,\n  delay / 60 AS delay_minutes\nFROM traindb.trips\nWHERE\n  $__timeFilter(timestamp) AND\n  train_name IN (${train_name:sqlstring})\nORDER BY timestamp\n"
    }
   ]
  },
  {
   "title": "Statistik Heute Insgesamt",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "dataset": "traindb",
     "rawSql": "SELECT\ntrain_name AS \"Zugname\", \nfahrt_nr AS \"Fahrtnummer\", \ndelay / 60 AS \"Verspätung in Min\"\nFROM traindb.today_delay_stats\nWHERE\n  train_name IN (${train_name:sqlstring}) AND fahrt_nr IN (${fahrt_nr:sqlstring})\nORDER BY train_name"
    }
   ]
  },
  {
   "title": "Statistik Insgesamt",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "dataset": "traindb",
     "rawSql": "SELECT\nfahrt_nr AS \"Fahrtnummer\", \ntotal_trips AS \"Züge insgesamt\",\ndelayed_trips AS \"Verspäte Züge\",\navg_delay / 60 AS \"Verspätung Avg\",\nmedian_delay / 60 AS \"Verspätung Median\"\nFROM traindb.delay_stats\nWHERE\n  fahrt_nr IN (${fahrt_nr:sqlstring})\nORDER BY fahrt_nr"
    }
   ]
  }
 ]
}